---
title: "OSF_PreRegistrationCopy"
author: "Holly Kirk"
date: "30 April 2018"
output:
  word_document: default
  pdf_document: default
---

## Title

Predicting avian movement ability and occurrence in urban environments.



## Authorship

Holly Kirk,
Luis Mata,
Sarah Bekessy



## Research Questions

Urban environments are typically made up of highly fragmented patches of habitat (either remnants or managed green spaces such as parks) surrounded by a matrix of land-uses generally considered to be non-habitat. One of the major assumptions in urban animal ecology is that species are capable of moving between these patches of habitat, across the urban matrix. Species movement ability is used to estimate the distance an animal could move to reach a new habitat patch, but often these movement estimates are based on data recorded in rural areas.

Using the City of Melbourne as a case study region we ask the following research questions:

_Given literature-derived estimates of bird movement capability, what is the predicted distribution of avian species?_

_Does the winter distribution of bird species in the area match the expected distribution?_

_Does land-use type effect the movement capability of bird species?_


# Hypotheses
1. Movement capability of birds in urban areas is lower than in rural areas.
2. Movement capability of birds in urban areas is mediated by land-use type.



## Sampling plan

# Existing data
Registration prior to creation of data: as of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realised.

Estimates for species’ movement capability outside urban environments will be drawn from the primary literature and used in the initial predictive models.


# Data collection procedures
The key variable to be measured in this study will be the abundance of bird species within the urban matrix. Data on current bird distributions within the study region will be collected using a point count survey methodology. Surveys will take place between May and August 2018 and will be undertaken by Holly Kirk. Sampling locations will be randomly selected within a 1.5km radius around each park (where locations fall within private property the surveyor will take a position as close to the point as possible). Points will be located more than 200m from each other.

Surveying will start at sunrise, and continue for a maximum of 3 hours, or until bird activity has noticeably reduced. After arriving at each survey location, all visible/audible bird individuals will be identified and recorded for a period of 10 minutes. This will include any birds seen flying overhead, and up to 50m away from the observer’s location (visibility permitting). In addition to bird species, environmental variables will also be recorded. These will include weather and site information. Surveys will not take place in the rain or strong winds (>40kmph).


# Sample size
At least 30 sampling locations outside of Royal Park and 20 outside Westgate Park. More if possible, but there are time constraints.


# Sample size rational
Sampling is principally constrained by available time; it must take place between May and August 2018. Fifty sampling locations represent an expected minimum number of surveys that can be completed during this time, accounting for interruptions incluuding variable weather conditions.


# Stopping rule
Data collection will be terminated at the end of July 2018, or after 100 surveys have been completed, whichever comes first.


# Variables
Manipulated


I am not manipulating any variables as this is an observational study. 


Measured


Bird species and abundance (count data) will be the outcome variable. Distance (m) from the park through each environment type/class (park, residential, industrial, road) will be used as predictors to test the hypotheses. Weather and site conditions will be assessed as potential confounding factors and included as predictors if necessary to meet model assumptions.

Additionally, estimates of movement ability for each species will be collated from the literature. These literature-derived estimates are likely to have different units (mean dispersal distance, maximum observed dispersal distance etc.) which, where possible, will be standardised to represent the mean dispersal distance by assuming an exponential movement distribution, and using existing formulae to estimate the parameter from the data.



## Design plan

# Study type
Observational study


# Blinding
No blinding is involved with this study


# Study design
An observational study, with random survey locations. 


# Randomization
Point survey locations will be selected uniformly at random within an area surrounding (and including) the parks.



## Analysis plan

# Statistical models
The number of individuals of each bird species or species group at each location will be used as the response variable in separate generalised linear models (GLMs) for each species with Poisson sampling distribution and log link.

To test hypothesis 1, the total distance of each survey point from the nearest edge of the park will be used as a predictor. The estimated slope coefficient will be interpreted as the decay parameter of an exponential movement distribution and compared with the parameter implied by the literature-derived estimate of movement ability. Hypothesis 1 will be tested separately for each species with a one-tailed one-sample t-test of whether the estimated urban dispersal parameter is lower than the existing dispersal parameter.

To test hypothesis 2, the straight-line distance from each survey point to the nearest edge of the park will be split into the distance traversing each habitat type (all habitat distances summing to the total distance). The distances for each habitat type will be used as multiple predictors in each species model, in place of the total distance. For each species, hypothesis 2 will be tested with a one-tailed likelihood ratio test between this habitat-dependent model and the habitat-independent model described above, testing whether the habitat-dependent model has better fit.

The validity of the assumptions made by these GLMs will be assessed by visualising model residuals. Where necessary, confounding factors (such as local site or weather conditions) will be accounted for by including them as additional predictors in the model. These predictors will be retained if they resolve any violations of model assumptions, but the corresponding parameter estimates will not be used to make inferences about hypotheses.


# Transformations
The data will not require transformation.


# Follow-up analyses
There will be no follow up analyses


# Inference criteria
P-values with a 0.05 cut off criterion. 


# Data exclusion
Models will be preferentially fitted for separate species, but where there are fewer than 10 total observations of a species, the observations for that species will be combined with counts for taxonomically and behaviourally similar species where possible, to form a species group. Where this is not possible, count data for those species will be excluded. Similarly, models will only be fit to species groups for which there are at least 10 observations.


# Missing data
There should not be any missing data.


# Exploratory analysis
No exploratory analyses will be performed.




